version: "3"
services:
  server:
    container_name: server
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
        - node-app
  db:
    container_name: db
    image: mongo
    environment:
      - PORT=27017
    volumes:
    - /data-vol:/data/db
      #- /data-vol:/data/db
  node-app:
    container_name: node-app
    restart: always
    build: ./serverapp
    environment:
      - PORT=8001
    links:
      - db
  nuxt-app:
    build: ./nordfin
    container_name: nuxt-app
    restart: always
    environment:
      - PORT=4000
    command: 'npm run start'