version: "2"
services:
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /usr/bin/docker/db/data:/apidb
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8001:8001"
    links:
      - db